/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../lib/api/axios-instance';
import type {
  AuthMeResponseDto,
  LandmarkDetailResponseDto,
  LandmarkDto,
  TourControllerGetLandmarksByRegionParams,
} from './model';

export const getAPIDocumentation = () => {
  const appControllerGetHello = () => {
    return customInstance<void>({ url: `/`, method: 'GET' });
  };

  const tourControllerGetLandmarksByRegion = (params: TourControllerGetLandmarksByRegionParams) => {
    return customInstance<LandmarkDto[]>({
      url: `/tour/landmarks/by-region`,
      method: 'GET',
      params,
    });
  };

  const tourControllerGetLandmarkDetail = (contentId: number) => {
    return customInstance<LandmarkDetailResponseDto>({
      url: `/tour/landmarks/${contentId}`,
      method: 'GET',
    });
  };

  const tourControllerGetLandmarks = () => {
    return customInstance<LandmarkDto[]>({ url: `/tour`, method: 'GET' });
  };

  /**
   * 토큰을 통해 인증된 유저의 정보를 가져옵니다.
   * @summary 내 정보 조회
   */
  const authControllerGetMe = () => {
    return customInstance<AuthMeResponseDto>({ url: `/auth/me`, method: 'GET' });
  };

  return {
    appControllerGetHello,
    tourControllerGetLandmarksByRegion,
    tourControllerGetLandmarkDetail,
    tourControllerGetLandmarks,
    authControllerGetMe,
  };
};
export type AppControllerGetHelloResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['appControllerGetHello']>>
>;
export type TourControllerGetLandmarksByRegionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarksByRegion']>>
>;
export type TourControllerGetLandmarkDetailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarkDetail']>>
>;
export type TourControllerGetLandmarksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarks']>>
>;
export type AuthControllerGetMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['authControllerGetMe']>>
>;
