/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../lib/api/axios-instance';
import type {
  BookmarkControllerGetBookmarksParams,
  BookmarkResponseDto,
  BookmarkStatusResponseDto,
  CreateBookmarkDto,
  LandmarkDetailResponseDto,
  LandmarkDto,
  TourControllerGetLandmarksByRegionParams,
} from './model';

export const getAPIDocumentation = () => {
  /**
   * API 서버의 상태를 확인합니다.
   * @summary Health check
   */
  const appControllerGetHello = () => {
    return customInstance<string>({ url: `/`, method: 'GET' });
  };

  /**
   * 시도 및 시군구 이름을 기반으로 해당 지역의 관광지 목록을 가져옵니다.
   * @summary 지역별 관광지 목록 조회
   */
  const tourControllerGetLandmarksByRegion = (params: TourControllerGetLandmarksByRegionParams) => {
    return customInstance<LandmarkDto[]>({
      url: `/tour/landmarks/by-region`,
      method: 'GET',
      params,
    });
  };

  /**
   * 콘텐츠 ID를 사용하여 관광지의 상세 정보, 이미지, 타입별 소개 정보를 가져옵니다.
   * @summary 관광지 상세 정보 조회
   */
  const tourControllerGetLandmarkDetail = (contentId: number) => {
    return customInstance<LandmarkDetailResponseDto>({
      url: `/tour/landmarks/${contentId}`,
      method: 'GET',
    });
  };

  /**
   * 시스템에 등록된 모든 관광지 목록을 페이지네이션 없이 가져옵니다.
   * @summary 전체 관광지 목록 조회
   */
  const tourControllerGetLandmarks = () => {
    return customInstance<LandmarkDto[]>({ url: `/tour`, method: 'GET' });
  };

  /**
   * 액세스 토큰을 분석하여 현재 인증된 사용자의 프로필 정보를 반환합니다.
   * @summary 내 정보 조회
   */
  const authControllerGetMe = () => {
    return customInstance<void>({ url: `/auth/me`, method: 'GET' });
  };

  /**
   * 특정 관광지를 사용자의 북마크 리스트에 추가합니다.
   * @summary 북마크 추가
   */
  const bookmarkControllerAddBookmark = (createBookmarkDto: CreateBookmarkDto) => {
    return customInstance<BookmarkResponseDto>({
      url: `/bookmarks`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createBookmarkDto,
    });
  };

  /**
   * 현재 로그인한 사용자의 모든 북마크 목록을 조회합니다.
   * @summary 내 북마크 목록 조회
   */
  const bookmarkControllerGetBookmarks = (params: BookmarkControllerGetBookmarksParams) => {
    return customInstance<BookmarkResponseDto[]>({ url: `/bookmarks`, method: 'GET', params });
  };

  /**
   * 관광지 콘텐츠 ID를 사용하여 북마크를 삭제합니다.
   * @summary 북마크 삭제
   */
  const bookmarkControllerRemoveBookmark = (contentId: number) => {
    return customInstance<void>({ url: `/bookmarks/${contentId}`, method: 'DELETE' });
  };

  /**
   * 특정 관광지가 사용자의 북마크에 등록되어 있는지 확인합니다.
   * @summary 북마크 여부 확인
   */
  const bookmarkControllerCheckBookmarkStatus = (contentId: number) => {
    return customInstance<BookmarkStatusResponseDto>({
      url: `/bookmarks/${contentId}/status`,
      method: 'GET',
    });
  };

  return {
    appControllerGetHello,
    tourControllerGetLandmarksByRegion,
    tourControllerGetLandmarkDetail,
    tourControllerGetLandmarks,
    authControllerGetMe,
    bookmarkControllerAddBookmark,
    bookmarkControllerGetBookmarks,
    bookmarkControllerRemoveBookmark,
    bookmarkControllerCheckBookmarkStatus,
  };
};
export type AppControllerGetHelloResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['appControllerGetHello']>>
>;
export type TourControllerGetLandmarksByRegionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarksByRegion']>>
>;
export type TourControllerGetLandmarkDetailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarkDetail']>>
>;
export type TourControllerGetLandmarksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['tourControllerGetLandmarks']>>
>;
export type AuthControllerGetMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['authControllerGetMe']>>
>;
export type BookmarkControllerAddBookmarkResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['bookmarkControllerAddBookmark']>>
>;
export type BookmarkControllerGetBookmarksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['bookmarkControllerGetBookmarks']>>
>;
export type BookmarkControllerRemoveBookmarkResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAPIDocumentation>['bookmarkControllerRemoveBookmark']>>
>;
export type BookmarkControllerCheckBookmarkStatusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAPIDocumentation>['bookmarkControllerCheckBookmarkStatus']>
  >
>;
