/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface BookmarkStatusResponseDto {
  /** 북마크 여부 */
  isBookmarked: boolean;
}
