/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type BookmarkControllerGetBookmarksParams = {
  /**
 * 페이지당 아이템 수
@default 20
 * @minimum 1
 * @maximum 100
 */
  limit?: number;
  /**
 * 건너뛸 아이템 수
@default 0
 * @minimum 0
 */
  offset: number;
};
