/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type BookmarkControllerGetBookmarksParams = {
  /**
 * 페이지당 항목 수
@default 20
 * @minimum 1
 * @maximum 100
 */
  limit?: number;
  /**
 * 건너뛸 항목 수 (오프셋)
@default 0
 * @minimum 0
 */
  offset: number;
};
