/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateBookmarkDto {
  /**
   * 랜드마크 콘텐츠 ID
   * @minimum 1
   */
  contentId: number;
}
