/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkImageDtoCpyrhtdivcd } from './landmarkImageDtoCpyrhtdivcd';
import type { LandmarkImageDtoSerialnum } from './landmarkImageDtoSerialnum';
import type { LandmarkImageDtoSmallimageurl } from './landmarkImageDtoSmallimageurl';

export interface LandmarkImageDto {
  contentid: number;
  originimgurl: string;
  imgname: string;
  smallimageurl?: LandmarkImageDtoSmallimageurl;
  cpyrhtdivcd?: LandmarkImageDtoCpyrhtdivcd;
  serialnum?: LandmarkImageDtoSerialnum;
}
