/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkDetailDtoAddr2 } from './landmarkDetailDtoAddr2';
import type { LandmarkDetailDtoAreacode } from './landmarkDetailDtoAreacode';
import type { LandmarkDetailDtoCat1 } from './landmarkDetailDtoCat1';
import type { LandmarkDetailDtoCat2 } from './landmarkDetailDtoCat2';
import type { LandmarkDetailDtoCat3 } from './landmarkDetailDtoCat3';
import type { LandmarkDetailDtoCpyrhtdivcd } from './landmarkDetailDtoCpyrhtdivcd';
import type { LandmarkDetailDtoCreatedtime } from './landmarkDetailDtoCreatedtime';
import type { LandmarkDetailDtoFirstimage2 } from './landmarkDetailDtoFirstimage2';
import type { LandmarkDetailDtoHomepage } from './landmarkDetailDtoHomepage';
import type { LandmarkDetailDtoLclssystm1 } from './landmarkDetailDtoLclssystm1';
import type { LandmarkDetailDtoLclssystm2 } from './landmarkDetailDtoLclssystm2';
import type { LandmarkDetailDtoLclssystm3 } from './landmarkDetailDtoLclssystm3';
import type { LandmarkDetailDtoLdongregncd } from './landmarkDetailDtoLdongregncd';
import type { LandmarkDetailDtoLdongsigngucd } from './landmarkDetailDtoLdongsigngucd';
import type { LandmarkDetailDtoMapx } from './landmarkDetailDtoMapx';
import type { LandmarkDetailDtoMapy } from './landmarkDetailDtoMapy';
import type { LandmarkDetailDtoMlevel } from './landmarkDetailDtoMlevel';
import type { LandmarkDetailDtoModifiedtime } from './landmarkDetailDtoModifiedtime';
import type { LandmarkDetailDtoSigungucode } from './landmarkDetailDtoSigungucode';
import type { LandmarkDetailDtoTel } from './landmarkDetailDtoTel';
import type { LandmarkDetailDtoZipcode } from './landmarkDetailDtoZipcode';

export interface LandmarkDetailDto {
  contentid: number;
  /** @nullable */
  contenttypeid?: number | null;
  title: string;
  /** @nullable */
  addr1?: string | null;
  addr2?: LandmarkDetailDtoAddr2;
  zipcode?: LandmarkDetailDtoZipcode;
  tel?: LandmarkDetailDtoTel;
  areacode?: LandmarkDetailDtoAreacode;
  sigungucode?: LandmarkDetailDtoSigungucode;
  cat1?: LandmarkDetailDtoCat1;
  cat2?: LandmarkDetailDtoCat2;
  cat3?: LandmarkDetailDtoCat3;
  mapx?: LandmarkDetailDtoMapx;
  mapy?: LandmarkDetailDtoMapy;
  mlevel?: LandmarkDetailDtoMlevel;
  /** @nullable */
  firstimage?: string | null;
  firstimage2?: LandmarkDetailDtoFirstimage2;
  cpyrhtdivcd?: LandmarkDetailDtoCpyrhtdivcd;
  createdtime?: LandmarkDetailDtoCreatedtime;
  modifiedtime?: LandmarkDetailDtoModifiedtime;
  ldongregncd?: LandmarkDetailDtoLdongregncd;
  ldongsigngucd?: LandmarkDetailDtoLdongsigngucd;
  lclssystm1?: LandmarkDetailDtoLclssystm1;
  lclssystm2?: LandmarkDetailDtoLclssystm2;
  lclssystm3?: LandmarkDetailDtoLclssystm3;
  homepage?: LandmarkDetailDtoHomepage;
  /** @nullable */
  overview?: string | null;
}
