/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkSummaryDto {
  /** 관광지 콘텐츠 ID */
  contentId: number;
  /** 관광지 제목 */
  title: string;
  /**
   * 대표 이미지 URL
   * @nullable
   */
  firstImage: string | null;
  /**
   * 주소
   * @nullable
   */
  addr1: string | null;
  /**
   * 대분류
   * @nullable
   */
  cat1: string | null;
  /**
   * 중분류
   * @nullable
   */
  cat2: string | null;
  /**
   * 소분류
   * @nullable
   */
  cat3: string | null;
}
