/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkDetailDto } from './landmarkDetailDto';
import type { LandmarkImageDto } from './landmarkImageDto';
import type { LandmarkIntroDto } from './landmarkIntroDto';

export interface LandmarkDetailResponseDto {
  detail: LandmarkDetailDto;
  images: LandmarkImageDto[];
  intro?: LandmarkIntroDto | null;
}
