/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkIntroDto {
  /** 콘텐츠 ID */
  contentid: number;
  /** 콘텐츠 타입 ID */
  contenttypeid: number;
  /**
   * 국가 지정 유산 1
   * @nullable
   */
  heritage1?: boolean | null;
  /**
   * 국가 지정 유산 2
   * @nullable
   */
  heritage2?: boolean | null;
  /**
   * 국가 지정 유산 3
   * @nullable
   */
  heritage3?: boolean | null;
  /**
   * 문의처 및 안내
   * @nullable
   */
  infocenter?: string | null;
  /**
   * 개장일
   * @nullable
   */
  opendate?: string | null;
  /**
   * 쉬는날
   * @nullable
   */
  restdate?: string | null;
  /**
   * 체험 안내
   * @nullable
   */
  expguide?: string | null;
  /**
   * 체험 가능 연령
   * @nullable
   */
  expagerange?: string | null;
  /**
   * 수용 인원
   * @nullable
   */
  accomcount?: string | null;
  /**
   * 이용 시기
   * @nullable
   */
  useseason?: string | null;
  /**
   * 이용 시간
   * @nullable
   */
  usetime?: string | null;
  /**
   * 주차 시설
   * @nullable
   */
  parking?: string | null;
  /**
   * 유모차 대여 여부
   * @nullable
   */
  chkbabycarriage?: boolean | null;
  /**
   * 애완동물 동반 가능 여부
   * @nullable
   */
  chkpet?: boolean | null;
  /**
   * 신용카드 가능 여부
   * @nullable
   */
  chkcreditcard?: boolean | null;
}
