/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type LandmarkDtoSigungucode = { [key: string]: unknown };
