/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkImageDto {
  /** 이미지 ID */
  id: number;
  /** 콘텐츠 ID */
  contentid: number;
  /** 원본 이미지 URL */
  originimgurl: string;
  /** 이미지 제목 */
  imgname: string;
  /**
   * 썸네일 이미지 URL
   * @nullable
   */
  smallimageurl?: string | null;
  /**
   * 저작권 유형
   * @nullable
   */
  cpyrhtdivcd?: string | null;
  /**
   * 일련번호
   * @nullable
   */
  serialnum?: string | null;
}
