/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkDetail {
  /** 획득 일시 */
  obtainedAt: string;
  /** 콘텐츠 ID */
  contentid: number;
  /** 제목 */
  title: string;
  /**
   * 대표 이미지 (원본)
   * @nullable
   */
  firstimage?: string | null;
}
