/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkDto {
  /** 콘텐츠 ID */
  contentid: number;
  /**
   * 콘텐츠 타입 ID (예: 12-관광지, 14-문화시설 등)
   * @nullable
   */
  contenttypeid?: number | null;
  /** 제목 */
  title: string;
  /**
   * 기본 주소
   * @nullable
   */
  addr1?: string | null;
  /**
   * 상세 주소
   * @nullable
   */
  addr2?: string | null;
  /**
   * 우편번호
   * @nullable
   */
  zipcode?: string | null;
  /**
   * 전화번호
   * @nullable
   */
  tel?: string | null;
  /**
   * 지역 코드
   * @nullable
   */
  areacode?: number | null;
  /**
   * 시군구 코드
   * @nullable
   */
  sigungucode?: number | null;
  /**
   * 대분류
   * @nullable
   */
  cat1?: string | null;
  /**
   * 중분류
   * @nullable
   */
  cat2?: string | null;
  /**
   * 소분류
   * @nullable
   */
  cat3?: string | null;
  /**
   * GPS X좌표 (경도)
   * @nullable
   */
  mapx?: number | null;
  /**
   * GPS Y좌표 (위도)
   * @nullable
   */
  mapy?: number | null;
  /**
   * 지도 레벨
   * @nullable
   */
  mlevel?: number | null;
  /**
   * 대표 이미지 URL
   * @nullable
   */
  firstimage?: string | null;
  /**
   * 썸네일 이미지 URL
   * @nullable
   */
  firstimage2?: string | null;
  /**
   * 저작권 구분 코드
   * @nullable
   */
  cpyrhtdivcd?: string | null;
  /**
   * 등록일
   * @nullable
   */
  createdtime?: string | null;
  /**
   * 수정일
   * @nullable
   */
  modifiedtime?: string | null;
  /**
   * 법정동 지역 코드
   * @nullable
   */
  ldongregncd?: number | null;
  /**
   * 법정동 시군구 코드
   * @nullable
   */
  ldongsigngucd?: number | null;
  /**
   * 분류 체계 1
   * @nullable
   */
  lclssystm1?: string | null;
  /**
   * 분류 체계 2
   * @nullable
   */
  lclssystm2?: string | null;
  /**
   * 분류 체계 3
   * @nullable
   */
  lclssystm3?: string | null;
}
