/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkDetailDto } from './landmarkDetailDto';
import type { LandmarkImageDto } from './landmarkImageDto';
import type { LandmarkIntroDto } from './landmarkIntroDto';

export interface LandmarkDetailResponseDto {
  /** 랜드마크 상세 정보 */
  detail: LandmarkDetailDto;
  /** 랜드마크 이미지 목록 */
  images: LandmarkImageDto[];
  /** 랜드마크 소개 정보 */
  intro?: LandmarkIntroDto | null;
  /** 스탬프 획득 여부 */
  isStamped: boolean;
}
