/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkIntroDto {
  /** 콘텐츠 ID */
  contentid: number;
  /** 콘텐츠 타입 ID */
  contenttypeid: number;
  /**
   * 세계문화유산 유무
   * @nullable
   */
  heritage1?: boolean | null;
  /**
   * 세계자연유산 유무
   * @nullable
   */
  heritage2?: boolean | null;
  /**
   * 세계기록유산 유무
   * @nullable
   */
  heritage3?: boolean | null;
  /**
   * 문의 및 안내
   * @nullable
   */
  infocenter?: string | null;
  /**
   * 개장일
   * @nullable
   */
  opendate?: string | null;
  /**
   * 쉬는날
   * @nullable
   */
  restdate?: string | null;
  /**
   * 체험프로그램
   * @nullable
   */
  expguide?: string | null;
  /**
   * 체험가능연령
   * @nullable
   */
  expagerange?: string | null;
  /**
   * 수용인원
   * @nullable
   */
  accomcount?: string | null;
  /**
   * 이용시기
   * @nullable
   */
  useseason?: string | null;
  /**
   * 이용시간
   * @nullable
   */
  usetime?: string | null;
  /**
   * 주차시설
   * @nullable
   */
  parking?: string | null;
  /**
   * 유모차 대여 여부
   * @nullable
   */
  chkbabycarriage?: boolean | null;
  /**
   * 애완동물 동반 가능 여부
   * @nullable
   */
  chkpet?: boolean | null;
  /**
   * 신용카드 정보
   * @nullable
   */
  chkcreditcard?: boolean | null;
}
