/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkDto {
  /** 콘텐츠 ID */
  contentid: number;
  /**
   * 콘텐츠 타입 ID
   * @nullable
   */
  contenttypeid?: number | null;
  /** 제목 */
  title: string;
  /**
   * 주소1
   * @nullable
   */
  addr1?: string | null;
  /**
   * 주소2
   * @nullable
   */
  addr2?: string | null;
  /**
   * 우편번호
   * @nullable
   */
  zipcode?: string | null;
  /**
   * 전화번호
   * @nullable
   */
  tel?: string | null;
  /**
   * 지역 코드
   * @nullable
   */
  areacode?: number | null;
  /**
   * 시군구 코드
   * @nullable
   */
  sigungucode?: number | null;
  /**
   * 대분류
   * @nullable
   */
  cat1?: string | null;
  /**
   * 중분류
   * @nullable
   */
  cat2?: string | null;
  /**
   * 소분류
   * @nullable
   */
  cat3?: string | null;
  /**
   * GPS X좌표 (경도)
   * @nullable
   */
  mapx?: number | null;
  /**
   * GPS Y좌표 (위도)
   * @nullable
   */
  mapy?: number | null;
  /**
   * 지도 레벨
   * @nullable
   */
  mlevel?: number | null;
  /**
   * 대표 이미지 (원본)
   * @nullable
   */
  firstimage?: string | null;
  /**
   * 대표 이미지 (썸네일)
   * @nullable
   */
  firstimage2?: string | null;
  /**
   * 저작권 유형
   * @nullable
   */
  cpyrhtdivcd?: string | null;
  /**
   * 등록일
   * @nullable
   */
  createdtime?: string | null;
  /**
   * 수정일
   * @nullable
   */
  modifiedtime?: string | null;
  /**
   * 법정동 코드
   * @nullable
   */
  ldongregncd?: number | null;
  /**
   * 법정동 시군구 코드
   * @nullable
   */
  ldongsigngucd?: number | null;
  /**
   * 지방자치단체 분류 1
   * @nullable
   */
  lclssystm1?: string | null;
  /**
   * 지방자치단체 분류 2
   * @nullable
   */
  lclssystm2?: string | null;
  /**
   * 지방자치단체 분류 3
   * @nullable
   */
  lclssystm3?: string | null;
}
