/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkDetailDto } from './landmarkDetailDto';
import type { LandmarkImageDto } from './landmarkImageDto';
import type { LandmarkIntroDto } from './landmarkIntroDto';

export interface LandmarkDetailResponseDto {
  /** 관광지 정보 상세 */
  detail: LandmarkDetailDto;
  /** 이미지 목록 */
  images: LandmarkImageDto[];
  /** 소개 정보 (관광지 타입별 상이) */
  intro?: LandmarkIntroDto | null;
}
