/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API Documentation
 * 프로젝트 API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkIntroDtoAccomcount } from './landmarkIntroDtoAccomcount';
import type { LandmarkIntroDtoChkbabycarriage } from './landmarkIntroDtoChkbabycarriage';
import type { LandmarkIntroDtoChkcreditcard } from './landmarkIntroDtoChkcreditcard';
import type { LandmarkIntroDtoChkpet } from './landmarkIntroDtoChkpet';
import type { LandmarkIntroDtoExpagerange } from './landmarkIntroDtoExpagerange';
import type { LandmarkIntroDtoExpguide } from './landmarkIntroDtoExpguide';
import type { LandmarkIntroDtoHeritage1 } from './landmarkIntroDtoHeritage1';
import type { LandmarkIntroDtoHeritage2 } from './landmarkIntroDtoHeritage2';
import type { LandmarkIntroDtoHeritage3 } from './landmarkIntroDtoHeritage3';
import type { LandmarkIntroDtoInfocenter } from './landmarkIntroDtoInfocenter';
import type { LandmarkIntroDtoOpendate } from './landmarkIntroDtoOpendate';
import type { LandmarkIntroDtoParking } from './landmarkIntroDtoParking';
import type { LandmarkIntroDtoRestdate } from './landmarkIntroDtoRestdate';
import type { LandmarkIntroDtoUseseason } from './landmarkIntroDtoUseseason';
import type { LandmarkIntroDtoUsetime } from './landmarkIntroDtoUsetime';

export interface LandmarkIntroDto {
  contentid: number;
  contenttypeid: number;
  heritage1?: LandmarkIntroDtoHeritage1;
  heritage2?: LandmarkIntroDtoHeritage2;
  heritage3?: LandmarkIntroDtoHeritage3;
  infocenter?: LandmarkIntroDtoInfocenter;
  opendate?: LandmarkIntroDtoOpendate;
  restdate?: LandmarkIntroDtoRestdate;
  expguide?: LandmarkIntroDtoExpguide;
  expagerange?: LandmarkIntroDtoExpagerange;
  accomcount?: LandmarkIntroDtoAccomcount;
  useseason?: LandmarkIntroDtoUseseason;
  usetime?: LandmarkIntroDtoUsetime;
  parking?: LandmarkIntroDtoParking;
  chkbabycarriage?: LandmarkIntroDtoChkbabycarriage;
  chkpet?: LandmarkIntroDtoChkpet;
  chkcreditcard?: LandmarkIntroDtoChkcreditcard;
}
