/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkDetail {
  /** 랜드마크 ID */
  landmarkId: number;
  /** 제목 */
  title: string;
  /**
   * 이미지 URL
   * @nullable
   */
  image: string | null;
  /** 획득 일시 */
  obtainedAt: string;
}
