/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkSummaryDto {
  contentId: number;
  title: string;
  /** @nullable */
  firstImage: string | null;
  /** @nullable */
  addr1: string | null;
  /** @nullable */
  cat1: string | null;
  /** @nullable */
  cat2: string | null;
  /** @nullable */
  cat3: string | null;
}
