/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LandmarkSummaryDto {
  /** 콘텐츠 ID */
  contentid: number;
  /** 제목 */
  title: string;
  /**
   * 대표 이미지 (원본)
   * @nullable
   */
  firstimage?: string | null;
  /**
   * 주소1
   * @nullable
   */
  addr1?: string | null;
  /**
   * 대분류
   * @nullable
   */
  cat1?: string | null;
  /**
   * 중분류
   * @nullable
   */
  cat2?: string | null;
  /**
   * 소분류
   * @nullable
   */
  cat3?: string | null;
}
