/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface MessageResponseDto {
  /** 응답 메시지 */
  message: string;
}
