/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LandmarkDetail } from './landmarkDetail';

export interface StampSummaryDto {
  /** 총 스탬프 개수 */
  totalCount: number;
  /** 획득한 랜드마크 목록 */
  landmarks: LandmarkDetail[];
}
