/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface StampResponseDto {
  /** 스탬프 ID */
  id: number;
  /** 사용자 화면 ID (UUID) */
  user_id: string;
  /** 랜드마크 ID */
  landmark_id: number;
  /** 생성일 */
  created_at: string;
}
