/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API 문서
 * Walkavel API 명세서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface UserResponseDto {
  /** 사용자 UUID */
  id: string;
  /** 사용자 이메일 */
  email?: string;
  /** 마지막 로그인 시각 */
  last_sign_in_at?: string;
}
